//! Fortran 2023 vocabulary additions that are not present in the legacy core tables.
//!
//! Keep these tables lowercase and sorted: callers use the core vocabulary's
//! case-insensitive binary-search helper.

/// Fortran 2023 language keywords.
pub static KEYWORDS: &[&str] = &[
    "classof",
    "doubleprecision",
    "endcritical",
    "endenum",
    "endprocedure",
    "endsubmodule",
    "endteam",
    "enumeration",
    "selectcase",
    "selectrank",
    "selecttype",
    "simple",
    "typeof",
];

/// Fortran 2023/current standard specifier words missing from the legacy table.
pub static SPECIFIERS: &[&str] = &["iolength", "named", "team_number"];

/// Optional-blank adjacent-keyword spellings from Fortran 2023 Table 6.2 that
/// are missing from the legacy compound table. `GO TO` has its own join policy,
/// and `IN OUT` is an INTENT specifier rather than a statement-head compound.
pub static COMPOUND_KEYWORDS: &[(&str, &str)] = &[
    ("doubleprecision", "double precision"),
    ("elsewhere", "else where"),
    ("endcritical", "end critical"),
    ("endenum", "end enum"),
    ("endprocedure", "end procedure"),
    ("endsubmodule", "end submodule"),
    ("endteam", "end team"),
];

/// Required-blank keyword pairs newly relevant to Fortran 2023 normalization.
pub static MULTIWORD_KEYWORD_PAIRS: &[(&str, &str)] = &[
    ("enumeration", "type"),
    ("notify", "wait"),
];

/// Standard intrinsic procedure names through Fortran 2023, including legacy specific names.
pub static INTRINSIC_PROCEDURES: &[&str] = &[
    "abs",
    "achar",
    "acos",
    "acosd",
    "acosh",
    "acospi",
    "adjustl",
    "adjustr",
    "aimag",
    "aint",
    "all",
    "allocated",
    "alog",
    "alog10",
    "amax0",
    "amax1",
    "amin0",
    "amin1",
    "amod",
    "anint",
    "any",
    "asin",
    "asind",
    "asinh",
    "asinpi",
    "associated",
    "atan",
    "atan2",
    "atan2d",
    "atan2pi",
    "atand",
    "atanh",
    "atanpi",
    "atomic_add",
    "atomic_and",
    "atomic_cas",
    "atomic_define",
    "atomic_fetch_add",
    "atomic_fetch_and",
    "atomic_fetch_or",
    "atomic_fetch_xor",
    "atomic_or",
    "atomic_ref",
    "atomic_xor",
    "bessel_j0",
    "bessel_j1",
    "bessel_jn",
    "bessel_y0",
    "bessel_y1",
    "bessel_yn",
    "bge",
    "bgt",
    "bit_size",
    "ble",
    "blt",
    "btest",
    "cabs",
    "ccos",
    "ceiling",
    "cexp",
    "char",
    "clog",
    "cmplx",
    "co_broadcast",
    "co_max",
    "co_min",
    "co_reduce",
    "co_sum",
    "command_argument_count",
    "conjg",
    "cos",
    "cosd",
    "cosh",
    "coshape",
    "cospi",
    "count",
    "cpu_time",
    "cshift",
    "csin",
    "csqrt",
    "ctan",
    "dabs",
    "dacos",
    "dasin",
    "datan",
    "datan2",
    "date_and_time",
    "dble",
    "dcos",
    "dcosh",
    "ddim",
    "dexp",
    "digits",
    "dim",
    "dint",
    "dlog",
    "dlog10",
    "dmax1",
    "dmin1",
    "dmod",
    "dnint",
    "dot_product",
    "dprod",
    "dshiftl",
    "dshiftr",
    "dsign",
    "dsin",
    "dsinh",
    "dsqrt",
    "dtan",
    "dtanh",
    "eoshift",
    "epsilon",
    "erf",
    "erfc",
    "erfc_scaled",
    "event_query",
    "execute_command_line",
    "exp",
    "exponent",
    "extends_type_of",
    "failed_images",
    "findloc",
    "float",
    "floor",
    "fraction",
    "gamma",
    "get_command",
    "get_command_argument",
    "get_environment_variable",
    "get_team",
    "huge",
    "hypot",
    "iabs",
    "iachar",
    "iall",
    "iand",
    "iany",
    "ibclr",
    "ibits",
    "ibset",
    "ichar",
    "idim",
    "idint",
    "idnint",
    "ieor",
    "ifix",
    "image_index",
    "image_status",
    "index",
    "int",
    "ior",
    "iparity",
    "is_contiguous",
    "is_iostat_end",
    "is_iostat_eor",
    "ishft",
    "ishftc",
    "isign",
    "kind",
    "lbound",
    "lcobound",
    "leadz",
    "len",
    "len_trim",
    "lge",
    "lgt",
    "lle",
    "llt",
    "log",
    "log10",
    "log_gamma",
    "logical",
    "maskl",
    "maskr",
    "matmul",
    "max",
    "max0",
    "max1",
    "maxexponent",
    "maxloc",
    "maxval",
    "merge",
    "merge_bits",
    "min",
    "min0",
    "min1",
    "minexponent",
    "minloc",
    "minval",
    "mod",
    "modulo",
    "move_alloc",
    "mvbits",
    "nearest",
    "new_line",
    "nint",
    "norm2",
    "not",
    "null",
    "num_images",
    "out_of_range",
    "pack",
    "parity",
    "popcnt",
    "poppar",
    "precision",
    "present",
    "product",
    "radix",
    "random_init",
    "random_number",
    "random_seed",
    "range",
    "rank",
    "real",
    "reduce",
    "repeat",
    "reshape",
    "rrspacing",
    "same_type_as",
    "scale",
    "scan",
    "selected_char_kind",
    "selected_int_kind",
    "selected_logical_kind",
    "selected_real_kind",
    "set_exponent",
    "shape",
    "shifta",
    "shiftl",
    "shiftr",
    "sign",
    "sin",
    "sind",
    "sinh",
    "sinpi",
    "size",
    "sngl",
    "spacing",
    "split",
    "spread",
    "sqrt",
    "stopped_images",
    "storage_size",
    "sum",
    "system_clock",
    "tan",
    "tand",
    "tanh",
    "tanpi",
    "team_number",
    "this_image",
    "tiny",
    "tokenize",
    "trailz",
    "transfer",
    "transpose",
    "trim",
    "ubound",
    "ucobound",
    "unpack",
    "verify",
];

/// Standard intrinsic module names.
pub static STANDARD_NAMES: &[&str] = &[
    "ieee_arithmetic",
    "ieee_exceptions",
    "ieee_features",
    "iso_c_binding",
    "iso_fortran_env",
];

/// Standard complex-part designators following `%`.
pub static COMPLEX_PART_DESIGNATORS: &[&str] = &["im", "re"];
